"""
Django settings for TimeMarket_BackEnd project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-87*r(fb$ur#dd9nkwu1(-+zfgwpr+5n_61zdtso=arl^j&grp)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# JWT 설정 예시
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 기본 5분 → 60분으로 연장
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}


ALLOWED_HOSTS = [
    'localhost', '127.0.0.1',  # 1. 로컬 PC (chrome)
    '10.0.2.2',  # 2. 에뮬레이터 (Android Studio)
    '172.30.1.50',  # 3. 로컬 PC가 사용하고 있는 ip 주소 (스마트폰으로 개발 시)
]

# settings.py
AUTH_USER_MODEL = 'users.User'


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",  # Channels 추가
    "chat",      # chat 앱 추가
    "wallet", "users", "map", "posts",
    "push_notice",  # 푸시 알림 앱 추가
    "corsheaders",  # 👈 1. 이 부분을 추가
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 👈 1. 이 부분을 가장 위에 추가
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "TimeMarket_BackEnd.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "TimeMarket_BackEnd.wsgi.application"
ASGI_APPLICATION = "TimeMarket_BackEnd.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# 미디어 작업
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# WebSocket을 위한 추가 설정 - 모든 포트 허용
ALLOWED_HOSTS = ['*']  # 모든 호스트 허용 (개발용)

# Firebase Admin SDK 자격증명 설정 (필요 시 환경변수로 교체)
FIREBASE_SERVICE_ACCOUNT_FILE = os.path.join(BASE_DIR, 'firebase-service-account.json')  # 실제 파일 경로로 교체

# 📌 1. 추가: CORS 설정 - 모든 오리진 허용 (개발용)
CORS_ALLOW_ALL_ORIGINS = True  # 모든 오리진 허용 (개발용)
# CORS_ALLOWED_ORIGINS는 CORS_ALLOW_ALL_ORIGINS=True일 때 무시됨

# WebSocket 연결을 위한 CORS 설정
CORS_ALLOW_CREDENTIALS = True

# 추가 CORS 헤더 허용
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]