# Generated by Django 5.2.1 on 2025-10-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_average_rating_user_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating_count',
        ),
    ]
