# Generated by Django 5.2.1 on 2025-10-09 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_traderequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traderequest",
            name="proposed_hours",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="제안 시간은 0.01시간 이상이어야 합니다."
                    ),
                    django.core.validators.MaxValueValidator(
                        999.99, message="제안 시간은 999.99시간을 초과할 수 없습니다."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="traderequest",
            name="proposed_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="제안 가격은 0.01원 이상이어야 합니다."
                    ),
                    django.core.validators.MaxValueValidator(
                        99999999.99, message="제안 가격은 99,999,999.99원을 초과할 수 없습니다."
                    ),
                ],
            ),
        ),
    ]
